### ISSUE TITLE
Error while creating iCal File

### ISSUE THREAD

**Issue by esva2** [humhub-contrib/external_calendar#26]
Hi,

I have problem with adding Google Calendar.

My humhub version is 1.8.2 + External Calendar 1.2.0.
![tempsnip](https://user-images.githubusercontent.com/83616630/116940320-7856b980-ac76-11eb-8b9b-9f069a41b73e.png)

In Log I can see this error:

_yii\base\InvalidValueException: Error while creating ical... Check if link is reachable. in /var/www/htdocs/example.com/demo/demo/protected/modules/external_calendar/models/ICalSync.php:80Stack trace: 
#0 /var/www/htdocs/example.com/demo/demo/protected/modules/external_calendar/controllers/CalendarController.php(108): humhub\modules\external_calendar\models\ICalSync->syncICal() 
#1 [internal function]: humhub\modules\external_calendar\controllers\CalendarController->actionEdit() 
#2 /var/www/htdocs/example.com/demo/demo/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() 
#3 /var/www/htdocs/example.com/demo/demo/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams() 
#4 /var/www/htdocs/example.com/demo/demo/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction() 
#5 /var/www/htdocs/example.com/demo/demo/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction() 
#6 /var/www/htdocs/example.com/demo/demo/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest() 
#7 /var/www/htdocs/example.com/demo/demo/index.php(25): yii\base\Application->run() 
#8 {main}_

**Comment by TorWaG77** [comment]
@esva2 I have the same problem (and the same log) with an ical-link to a Synology-Diskstation. Do yo have meanwhile a solution or a hint? Thx, Torsten

**Comment by punkyard** [comment]
hi
me too
i first used subscription links, and it worked for a while.
Now it stopped functioning, with the same type of message.

Have you had a chance to identify the dificulty? can you share please?

**Comment by funkycram** [comment]
Could be related to https://github.com/humhub-contrib/external_calendar/issues/47
