### ISSUE TITLE
Unactionable error message: Fehler beim Erstellen der iCal-Datei... Überprüfen Sie, ob der Link erreichbar ist.

### ISSUE THREAD

**Issue by dreua** [humhub-contrib/external_calendar#32]
As a server administrator I see the following message and I honestly don't know what do do about it: There is no information on which space / calendar is causing this or the affected URL.

Furthermore I'd suggest to avoid translating error messages because it makes it harder to find solutions online and to discuss those errors in an international community.

```
yii\base\InvalidValueException: Fehler beim Erstellen der iCal-Datei... Überprüfen Sie, ob der Link erreichbar ist. in /srv/www/htdocs/[redacted]/modules/external_calendar/models/ICalSync.php:80
Stack trace:
#0 /srv/www/htdocs/[redacted]/modules/external_calendar/models/ICalSync.php(68): humhub\modules\external_calendar\models\ICalSync->syncICal()
#1 /srv/www/htdocs/[redacted]/modules/external_calendar/models/ExternalCalendar.php(408): humhub\modules\external_calendar\models\ICalSync::sync(Object(humhub\modules\external_calendar\models\ExternalCalendar), NULL, NULL)
#2 /srv/www/htdocs/[redacted]/modules/external_calendar/jobs/SyncHourly.php(27): humhub\modules\external_calendar\models\ExternalCalendar->sync()
#3 /srv/humhub/protected/humhub/modules/queue/ActiveJob.php(33): humhub\modules\external_calendar\jobs\SyncHourly->run()
#4 /srv/humhub/protected/vendor/yiisoft/yii2-queue/src/Queue.php(246): humhub\modules\queue\ActiveJob->execute(Object(humhub\modules\queue\driver\MySQL))
#5 /srv/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('12165264', 'O:48:"humhub\\mo...', '300', '1')
#6 /srv/humhub/protected/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute('12165264', 'O:48:"humhub\\mo...', '300', '1', '27397')
#7 [internal function]: yii\queue\cli\Command->actionExec('12165264', '300', '1', '27397')
#8 /srv/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#10 /srv/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('exec', Array)
#11 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('exec', Array)
#12 /srv/humhub/protected/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('queue/exec', Array)
#13 /srv/humhub/protected/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application->runAction('queue/exec', Array)
#14 /srv/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(yii\console\Request))
#15 /srv/www/htdocs/[redacted]/yii.php(38): yii\base\Application->run()
#16 {main}
```

**Comment by man10to** [comment]
Sun, 30 Jan 2022 15:46:25 +0100  application
yii\base\InvalidValueException: Fehler beim Erstellen der iCal-Datei... Überprüfen Sie, ob der Link erreichbar ist. in /mnt/web506/c3/03/510452503/htdocs/humhub/protected/modules/external_calendar/models/ICalSync.php:80
Stack trace:
#0 /mnt/web506/c3/03/510452503/htdocs/humhub/protected/modules/external_calendar/models/ICalSync.php(68): humhub\modules\external_calendar\models\ICalSync->syncICal()
