### ISSUE TITLE
last updates didn't fix the issues of the module

### ISSUE THREAD

**Issue by punkyard** [humhub-contrib/external_calendar#41]
Hi
hh 1-13-0 and external-calendar 1.3.2 didn't fix my issues
which I can't understand, has my links (created by nextcloud) worked fine until not anymore. I can't find the origin of the problem.

Our calendars don't work, it's really a problem for us.
Would one just take a quick look at our log please?

Thanks

`WARNING  Thu, 29 Dec 2022 09:54:18 +0100 application
yii\base\InvalidValueException: Error while creating ical... Check if link is reachable. in /home/protected/modules/external_calendar/models/ICalSync.php:80
Stack trace:
#0 /home/protected/modules/external_calendar/controllers/CalendarController.php(108): humhub\modules\external_calendar\models\ICalSync->syncICal()
#1 [internal function]: humhub\modules\external_calendar\controllers\CalendarController->actionEdit()
#2 /home/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 /home/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#4 /home/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#5 /home/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#6 /home/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#7 /home/index.php(25): yii\base\Application->run()`

`INFO  Thu, 29 Dec 2022 09:54:18 +0100 application
$_GET = [
'_pjax' => '#layout-content'
'_' => '1672267632640'
'cguid' => '4e33ef41-745d-4370-8b01-ac95cd2841de'
]

$_SERVER = [
'TEMP' => '/home/tmp'
'TMPDIR' => '/home/tmp'
'TMP' => '/home/tmp'
'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
'USER' => 'myself'
'HOME' => '/home/'
'SCRIPT_NAME' => '/index.php'
'REQUEST_URI' => '/s/053/external_calendar/calendar/edit?_pjax=%23layout-content&_=1672267632640'
'QUERY_STRING' => '_pjax=%23layout-content&_=1672267632640'
'REQUEST_METHOD' => 'POST'
'SERVER_PROTOCOL' => 'HTTP/1.0'
'GATEWAY_INTERFACE' => 'CGI/1.1'
'REDIRECT_QUERY_STRING' => '_pjax=%23layout-content&_=1672267632640'
'REDIRECT_URL' => '/s/053/external_calendar/calendar/edit'
'REMOTE_PORT' => '38662'
'SCRIPT_FILENAME' => '/home/index.php'
'SERVER_ADMIN' => 'info@mon.domaine.net'
'CONTEXT_DOCUMENT_ROOT' => '/home/'
'CONTEXT_PREFIX' => ''
'REQUEST_SCHEME' => 'https'
'DOCUMENT_ROOT' => '/home/'
'REMOTE_ADDR' => '12.345.123.123'
'SERVER_PORT' => '443'
'SERVER_ADDR' => '12.345.123.123'
'SERVER_NAME' => 'mon.domaine.net'
'SERVER_SOFTWARE' => 'Apache/2.4.54 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/3.0.2'
'SERVER_SIGNATURE' => ''
'HTTP_COOKIE' => '_identity=111; PHPSESSID=222; _; language=333language00en-US; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true'
'HTTP_CF_CONNECTING_IP' => '12.345.123.123'
'HTTP_REFERER' => 'https://mon.domaine.net/s/053/external_calendar/calendar/edit?_pjax=%23layout-content&_=123'
'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15'
'HTTP_ACCEPT_LANGUAGE' => 'fr-fr'
'HTTP_ORIGIN' => 'https://mon.domaine.net'
'CONTENT_TYPE' => 'application/x-www-form-urlencoded'
'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
'HTTP_CF_VISITOR' => '{\"scheme\":\"https\"}'
'HTTP_X_FORWARDED_PROTO' => 'https'
'HTTP_CF_RAY' => '111-CDG'
'HTTP_ACCEPT_ENCODING' => 'gzip'
'HTTP_CDN_LOOP' => 'cloudflare'
'HTTP_CF_IPCOUNTRY' => 'FR'
'CONTENT_LENGTH' => '419'
'HTTP_CONNECTION' => 'close'
'HTTP_X_FORWARDED_FOR' => '12.345.123.123, 12.345.123.123'
'HTTP_HOST' => 'mon.domaine.net'
'proxy-nokeepalive' => '1'
'HTTPS' => 'on'
'REDIRECT_STATUS' => '200'
'REDIRECT_HTTPS' => 'on'
'FCGI_ROLE' => 'RESPONDER'
'PHP_SELF' => '/index.php'
'REQUEST_TIME_FLOAT' => 111.1111
'REQUEST_TIME' => 123456789
]`

**Comment by funkycram** [comment]
Could be related to https://github.com/humhub-contrib/external_calendar/issues/47
