### ISSUE TITLE
Export link url doesn't work any more

### ISSUE THREAD

**Issue by bodjelo** [humhub-contrib/external_calendar#46]
Hi,

The public iCal link doesn't work any more.
I have this in the logs : 

INFO  Thu, 25 May 2023 10:06:01 +0200 
$_GET = []

$_SERVER = [
'HOME' => '/var/www'
'LOGNAME' => 'www-data'
'PATH' => '/usr/bin:/bin'
'LANG' => 'C.UTF-8'
'SHELL' => '/bin/sh'
'PWD' => '/var/www'
'PHP_SELF' => '/var/www/html/humhub/protected/yii'
'SCRIPT_NAME' => '/var/www/html/humhub/protected/yii'
'SCRIPT_FILENAME' => '/var/www/html/humhub/protected/yii'
'PATH_TRANSLATED' => '/var/www/html/humhub/protected/yii'
'DOCUMENT_ROOT' => ''
'REQUEST_TIME_FLOAT' => 1685001961.3557
'REQUEST_TIME' => 1685001961
'argv' => [
0 => '/var/www/html/humhub/protected/yii'
1 => 'cron/run'
]
'argc' => 2
]

ERREUR  Thu, 25 May 2023 10:06:01 +0200 application
yii\base\UnknownMethodException: Calling unknown method: humhub\components\console\Application::getSession() in /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/User.php(690): yii\base\Component->__call()
#1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/User.php(199): yii\web\User->renewAuthStatus()
#2 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/User.php(367): yii\web\User->getIdentity()
#3 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User->getIsGuest()
#4 /var/www/html/humhub/protected/modules/calendar/interfaces/event/AbstractCalendarQuery.php(312): yii\base\Component->__get()
#5 /var/www/html/humhub/protected/modules/calendar/interfaces/event/AbstractCalendarQuery.php(226): humhub\modules\calendar\interfaces\event\AbstractCalendarQuery::find()
#6 /var/www/html/humhub/protected/modules/calendar/models/CalendarEntryQuery.php(72): humhub\modules\calendar\interfaces\event\AbstractCalendarQuery::findForFilter()
#7 /var/www/html/humhub/protected/modules/calendar/interfaces/CalendarService.php(152): humhub\modules\calendar\models\CalendarEntryQuery::findForFilter()
#8 /var/www/html/humhub/protected/modules/calendar/interfaces/CalendarService.php(207): humhub\modules\calendar\interfaces\CalendarService->getCalendarItems()
#9 /var/www/html/humhub/protected/modules/calendar/models/reminder/ReminderProcessor.php(82): humhub\modules\calendar\interfaces\CalendarService->getUpcomingEntries()
#10 /var/www/html/humhub/protected/modules/calendar/models/reminder/ReminderProcessor.php(63): humhub\modules\calendar\models\reminder\ReminderProcessor->runByUpcomingEvents()
#11 /var/www/html/humhub/protected/modules/calendar/models/reminder/ReminderService.php(20): humhub\modules\calendar\models\reminder\ReminderProcessor->run()
#12 /var/www/html/humhub/protected/modules/calendar/Events.php(377): humhub\modules\calendar\models\reminder\ReminderService->sendAllReminder()
#13 [internal function]: humhub\modules\calendar\Events::onCronRun()
#14 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#15 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php(642): yii\base\Event::trigger()
#16 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(297): yii\base\Component->trigger()
#17 /var/www/html/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(86): yii\base\Controller->beforeAction()
#18 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(176): yii\console\Controller->beforeAction()
#19 /var/www/html/humhub/protected/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#20 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction()
#21 /var/www/html/humhub/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#22 /var/www/html/humhub/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#23 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest()
#24 /var/www/html/humhub/protected/yii(29): yii\base\Application->run()
#25 {main}

Can you please help me ?

Humhub community edition v1.14.2
External Calendar v 1.3.3

**Comment by bodjelo** [comment]
Solved with today's new version (1.4.0)
